"""create traffic observations table

Revision ID: 38007b3cb704
Revises: 4f24f48b7afb
Create Date: 2026-09-02 15:41:18.577143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38007b3cb704'
down_revision: Union[str, Sequence[str], None] = '4f24f48b7afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_speed', sa.Float(), nullable=True),
    sa.Column('reference_speed', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_observations_observed_at'), 'traffic_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_traffic_observations_road_id'), 'traffic_observations', ['road_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_observations_road_id'), table_name='traffic_observations')
    op.drop_index(op.f('ix_traffic_observations_observed_at'), table_name='traffic_observations')
    op.drop_table('traffic_observations')
    # ### end Alembic commands ###
